[phases.setup]
nixPkgs = ['nodejs_22', 'nodePackages.pnpm']

[phases.install]
cmds = ['pnpm config set auto-install-peers true', 'pnpm install']

[phases.build]
cmds = ['chmod +x ./scripts/build.sh', './scripts/build.sh']

[start]
cmd = 'pnpm --dir packages/agent start'

[variables]
NODE_ENV = 'production'
