name: ci

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: pnpm/action-setup@v3
              with:
                  version: 9.4.0

            - name: Install dependencies
              run: pnpm i

            - name: Run Prettier
              run: pnpm run prettier --check .

            - name: Build packages
              run: pnpm run build
